Controllers/WorkerController.cs
using BaristaHome.Data;
using BaristaHome.Migrations;
using BaristaHome.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Security.Claims;
using System.Text;
using System.Web.Helpers;

namespace BaristaHome.Controllers
{
    /*[Authorize]*/
    public class WorkerController : Controller
    {
        /*[Authorize(Policy = "AdminOnly")]*/
        private readonly BaristaHomeContext _context;

        public WorkerController(BaristaHomeContext context)
        {
            _context = context;
        }

        public IActionResult Worker()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        //Display list of workers that belong to the store
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var workers = await _context.User
                            .Where(u => u.StoreId == Convert.ToInt16(User.FindFirst("StoreId").Value))
                            .OrderByDescending(u => u.RoleId)
                            .ThenBy(u => u.FirstName)
                            .ToListAsync();

            return View(workers);
        }

        //Return a worker edit page for the current user
        public async Task<IActionResult> WorkerEdit()
        {
            return View(await _context.User.FirstOrDefaultAsync(m => m.UserId.ToString() == User.FindFirst("UserId").Value));
        }

        //Return a details page for the current user
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var worker = await _context.User
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (worker == null)
            {
                return NotFound();
            }

            return View(worker);
        }


        //Retrieve all input from the worker edit page, and then update the user model and save the user model in the database
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>
            WorkerEdit([Bind(include: ("UserId,FirstName,LastName,Email,Password,ConfirmPassword,Color,InviteCode,RoleId,StoreId,UserImageData,UserImage,UserDescription,Image"))] User worker)
        {

            var existingEmail = (from u in _context.User
                                 where u.Email.Equals(worker.Email) && !u.UserId.Equals(worker.UserId)
                                 select u).FirstOrDefault();

            if (existingEmail != null)
            {
                ModelState.AddModelError(string.Empty, "The email you are trying to change already exists on another account! Please use a different one.");
                return View(worker);
            }

            //Saves worker image as a byte array
            if (worker.Image != null)
            {
                using (var ms = new MemoryStream())
                {
                    worker.Image.CopyTo(ms);
                    var fileBytes = ms.ToArray();
                    worker.UserImageData = fileBytes;
                }
            }

            var w = await _context.User.FirstOrDefaultAsync(m => m.UserId.ToString() == User.FindFirst("UserId").Value);
            w.FirstName = worker.FirstName;
            w.LastName = worker.LastName;
            w.Email = worker.Email;
            w.Image = worker.Image;
            w.UserImage = worker.UserImage;
            w.UserImageData = worker.UserImageData;

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(w);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WorkerExists(worker.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            return View(w);
        }

        //Return owner editing page based on their id
        public async Task<IActionResult> OwnerEdit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var worker = await _context.User.FindAsync(id);
            if (worker == null)
            {
                return NotFound();
            }
            return View(worker);
        }


        //Updates and saves any new changes inputted by the user
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> OwnerEdit(User worker)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(worker);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(worker);
        }

        //Returns an owner self editing page based on their id
        public async Task<IActionResult> OwnerSelfEdit()
        {
            return View(await _context.User.FirstOrDefaultAsync(m => m.UserId.ToString() == User.FindFirst("UserId").Value));
        }



        //Saves any new changes to the user information inputted by the user
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> OwnerSelfEdit([Bind(include: ("UserId,FirstName,LastName,Email,Password,ConfirmPassword,Color,InviteCode,RoleId,StoreId,UserImageData,UserImage,UserDescription,Image"))] User worker)
        {
            worker.Password = Crypto.HashPassword(worker.Password);
            worker.ConfirmPassword = worker.Password;

            var existingEmail = (from u in _context.User
                                 where u.Email.Equals(worker.Email) && !u.UserId.Equals(worker.UserId)
                                 select u).FirstOrDefault();

            if (existingEmail != null)
            {
                ModelState.AddModelError(string.Empty, "The email you are trying to change already exists on another account! Please use a different one.");
                return View(worker);
            }

            //Saves worker image as a byte array
            if (worker.Image != null)
            {
                using (var ms = new MemoryStream())
                {
                    worker.Image.CopyTo(ms);
                    var fileBytes = ms.ToArray();
                    worker.UserImageData = fileBytes;
                }
            }

            var w = await _context.User.FirstOrDefaultAsync(m => m.UserId.ToString() == User.FindFirst("UserId").Value);
            w.FirstName = worker.FirstName;
            w.LastName = worker.LastName;
            w.Email = worker.Email;
            w.Color = worker.Color;
            w.Image = worker.Image;
            w.UserImage = worker.UserImage;
            w.UserImageData = worker.UserImageData;


            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(w);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction("Index", "Home");
            }
            return View(w);
        }


        // Returns a delete page based on the selected user's id
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var worker = await _context.User
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (worker == null)
            {
                return NotFound();
            }

            return View(worker);
        }


        // Removes the selected user from the database
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var worker = await _context.User.FindAsync(id);
            _context.User.Remove(worker);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WorkerExists(int id)
        {
            return _context.User.Any(worker => worker.UserId == id);
        }

        //Displays an invite code page based on the user id
        public async Task<IActionResult> Invite()
        {
            return View(await _context.User.FirstOrDefaultAsync(m => m.UserId.ToString() == User.FindFirst("UserId").Value));
        }

        //Displays user profile based on the user id
        public async Task<IActionResult> Profile()
        {
            return View(await _context.User.FirstOrDefaultAsync(m => m.UserId.ToString() == User.FindFirst("UserId").Value));
        }

        //Returns the current users image to the view
        public async Task<ActionResult> RenderImage(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var worker = await _context.User.FirstOrDefaultAsync(m => m.UserId == id);
            if (worker == null)
            {
                return NotFound();
            }
            var image = (from w in _context.User

Views/Worker/ChangePassword.cshtml
@model BaristaHome.Models.User

@{
    ViewData["Title"] = "ChangePassword •";
}

<style>
    .edit-button {
        background-color: white;
        border-color: rgba(219, 113, 152, 0.67);
        color: rgba(219, 113, 152, 0.67);
        height: 45px;
        width: 120px;
        border-style: solid;
        transition: background-color 0.15s, color 0.15s;
    }

    .page-title {
        display: flex;
        padding-bottom: 30px;
        font-size: 30px;
        padding-left: 20px;
        font-weight: 500;
    }

    .background {
        background-color: antiquewhite;
        box-shadow: 1px 1px 0 rgba(0, 0, 0, 0.15);
        padding-top: 30px;
        padding-bottom: 30px;
        padding-left: 50px;
        padding-right: 50px;
    }

    .pink-button {
        background-color: pink;
        color: black;
        border: none;
        padding-top: 10px;
        padding-bottom: 10px;
        padding-left: 20px;
        padding-right: 20px;
        margin-bottom: 10px;
        box-shadow: 1px 1px 1px 0 rgba(0, 0, 0, 0.15);
        transition: background-color 0.15s, color 0.15s;
        display: inline-block;
    }

    .pink-button:hover {
        background-color: lightpink;
        cursor: pointer;
    }

    .pink-button:active {
        background-color: rgba(219, 113, 152, 0.67);
    }


    .edit-button:hover {
        background-color: lightpink;
        border-color: lightpink;
        color: white;
    }

    .center {
        width: 75%;
        text-align: center;
    }
</style>

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color:#ffdcf4">
        @if (Model.RoleId == 1 || Model.RoleId == 2)
        {
            <a class="nav-link pink-button-left" asp-controller="Worker" asp-action="WorkerEdit">Back</a>
        }
        else
        {
            <a class="nav-link pink-button-left" asp-controller="Worker" asp-action="OwnerSelfEdit">Back</a>
        }

        <div class="center">
            <h1 class="title">Profile</h1>
        </div>
    </nav>
</header>

<div style="padding-left: 200px; padding-right:200px;  padding-top: 50px;">
    <div class="background">

        <div style="vertical-align:middle;">
            <p class="page-title">Change Password</p>

            <div class="row">
                <div class="col-md-4">

                    <form asp-action="ChangePassword">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="UserId" />
                        <input type="hidden" asp-for="FirstName" />
                        <input type="hidden" asp-for="LastName" />
                        <input type="hidden" asp-for="Email" />
                        <input type="hidden" asp-for="Color" />
                        <input type="hidden" asp-for="InviteCode" />
                        <input type="hidden" asp-for="UserImage" />
                        <input type="hidden" asp-for="UserImageData" />
                        <input type="hidden" asp-for="RoleId" />
                        <input type="hidden" asp-for="UserDescription" />
                        <input type="hidden" asp-for="Wage" />
                        <input type="hidden" asp-for="StoreId" />


                        <div class="form-group">
                            <label asp-for="Password" class="control-label"></label>
                            <input asp-for="Password" class="form-control" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="ConfirmPassword" class="control-label"></label>
                            <input asp-for="ConfirmPassword" class="form-control" />
                            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                        </div>



                        <input type="submit" value="Save" style="margin-top: 10px;" class="pink-button" />



                    </form>
                </div>
            </div>

        </div>

    </div>


</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Worker/Delete.cshtml
@model BaristaHome.Models.User

@{
    ViewData["Title"] = "Delete •";
}

<style>
    a {
        color: inherit;
        text-decoration: none;
    }
    .page-title {
        display: flex;
        padding-bottom: 10px;
        font-size: 30px;
        padding-left: 20px;
        font-weight: 500;
    }

    .background {
        background-color: antiquewhite;
        box-shadow: 1px 1px 0 rgba(0, 0, 0, 0.15);
        padding-top: 30px;
        padding-bottom: 30px;
        padding-left: 30px;
        padding-right: 30px;
    }


    .pink-button {
        background-color: #ffdcf4;
        color: black;
        border: none;
        width: 70px;
        height:40px;
        box-shadow: 1px 1px 1px 0 rgba(0, 0, 0, 0.15);
        transition: background-color 0.15s, color 0.15s;
    }

    .pink-button:hover {
        background-color: lightpink;
        cursor: pointer;
    }

    .pink-button:active {
        background-color: rgba(219, 113, 152, 0.67);
    }

    .center {
        width: 75%;
        text-align: center;
    }
</style>

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color:#ffdcf4">
        <a class="nav-link pink-button-left" asp-controller="Worker" asp-action="Index">Back</a>

        <div class="center">
            <h1 class="title">Worker Management</h1>
        </div>
    </nav>
</header>

<div style="padding-left: 200px; padding-right:200px;  padding-top: 50px;">

    <div class="background">
        <p class="page-title">Delete</p>

        <div>
            <h4>Are you sure you want to delete this worker?</h4>

            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.FirstName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.FirstName)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.LastName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.LastName)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Email)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Email)
                </dd>

            </dl>

            <form asp-action="Delete">
                <input type="hidden" asp-for="UserId" />
                <input type="submit" value="Delete" class="pink-button" />
            </form>
        </div>
    </div>


</div>

Views/Worker/Details.cshtml
@model BaristaHome.Models.User

@{
    ViewData["Title"] = "Details •";
}

@*details, worker controller*@


<style>

    a {
        color: inherit;
        text-decoration: none;
    }

    .profile-pic {
        border-radius: 200px;
        height: 230px;
        width: 230px;
        object-fit: cover;
        display: flex;
        margin-right: 50px;
    }

    .profile-info {
        display: flex;
    }

    .profile {
        display: flex;
        flex-direction: row;
        padding-top: 10px;
        padding-bottom: 100px;
        padding-left: 30px;
        padding-right: 30px;
    }

    .page-title {
        display: flex;
        padding-bottom: 30px;
        font-size: 30px;
        padding-left: 20px;
        font-weight: 500;
    }

    .background {
        background-color: antiquewhite;
        box-shadow: 1px 1px 0 rgba(0, 0, 0, 0.15);
        padding-top: 30px;
        padding-bottom: 30px;
        padding-left: 30px;
        padding-right: 30px;
    }

    .pink-button {
        background-color: #ffdcf4;
        color: black;
        border: none;
        padding-top: 10px;
        padding-bottom: 10px;
        padding-left: 20px;
        padding-right: 20px;
        margin-bottom: 10px;
        box-shadow: 1px 1px 1px 0 rgba(0, 0, 0, 0.15);
        transition: background-color 0.15s, color 0.15s;
    }

        .pink-button:hover {
            background-color: lightpink;
            cursor: pointer;
        }

        .pink-button:active {
            background-color: rgba(219, 113, 152, 0.67);
        }

    .user-profile-title-and-button-row {
        display: flex;
        flex-direction: row;
        justify-content: space-between;
    }

    .edit-button {
        background-color: white;
        border-color: rgba(219, 113, 152, 0.67);
        color: rgba(219, 113, 152, 0.67);
        height: 45px;
        width: 120px;
        border-style: solid;
    }

    .center {
        width: 75%;
        text-align: center;
    }
</style>

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color:#ffdcf4">
        <a class="nav-link pink-button-left" asp-controller="Worker" asp-action="Index">Back</a>

        <div class="center">
            <h1 class="title">Worker Management</h1>
        </div>
    </nav>
</header>

<div style="padding-left: 200px; padding-right:200px;  padding-top: 50px;">
    <div class="background">

        <div class="user-profile-title-and-button-row">
            <div class="page-title"> Information </div>
        </div>

        <div class="profile">
            <label>
                @if (Model.UserImageData == null)
                {
                    <img class="profile-pic" src="../images/default-profile-pic.jpg" style="background-color: white; border: 3px solid #DFB3D3">
                }
                else
                {
                    <img class="profile-pic" src="@Url.Action("RenderImage", new { id = Model.UserId})" style="background-color: white; border: 3px solid #DFB3D3" />
                }
            </label>

            <div class="profile-info">
                <hr />
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.FirstName)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.FirstName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.LastName)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.LastName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Email)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Email)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Role)
                    </dt>
                    <dd class="col-sm-10">
                        @if (Model.RoleId == (1))
                        {
                            <p>Worker</p>
                        }
                        else if (Model.RoleId == 2)
                        {
                            <p>Manager</p>
                        }
                        else
                        {
                            <p>Owner</p>
                        }
                    </dd>
                    <dt class="col-sm-2">
                        @if (Model.RoleId == 1)
                        {
                            @Html.DisplayNameFor(model => model.Wage)
                        }
                    </dt>
                    <dd class="col-sm-10">
                        @if (Model.RoleId == 1)
                        {
                            @if (Model.Wage == null)
                            {
                                <p>Wage has not been specified.</p>
                            }
                            else
                            {
                                @Html.DisplayFor(model => model.Wage)
                            }
                        }

                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Color)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Color)
                    </dd>
                    <dt class="col-sm-2">
                        @if (Model.RoleId != 3)
                        {
                            <p>User Description</p>
                        }
                    </dt>
                    <dd class="col-sm-10">
                        @if (Model.RoleId != 3)
                        {
                            @Html.DisplayFor(model => model.UserDescription)
                        }

                    </dd>
                </dl>
            </div>

        </div>
    </div>
</div>

Views/Worker/Index.cshtml
@model IEnumerable<BaristaHome.Models.User>

@{
    ViewData["Title"] = "Worker Management •";
}

@*index page for worker controller*@
<style>
    a {
        color: inherit;
        text-decoration: none;
    }

    .page-title {
        display: inline-block;
        padding-bottom: 30px;
        font-size: 30px;
        padding-left: 20px;
        font-weight: 500;
    }

    .pink-button {
        background-color: #ffdcf4;
        color: black;
        border: none;
        height: 50px;
        width: 200px;
        box-shadow: 1px 1px 1px 0 rgba(0, 0, 0, 0.15);
        transition: background-color 0.15s, color 0.15s;
        padding: 0.8rem 1.8rem;
    }

    .pink-button:hover {
        background-color: lightpink;
        cursor: pointer;
    }

    .pink-button:active {
        background-color: rgba(219, 113, 152, 0.67);
    }

    .background {
        background-color: antiquewhite;
        box-shadow: 1px 1px 0 rgba(0, 0, 0, 0.15);
        padding-top: 30px;
        padding-bottom: 30px;
        padding-left: 30px;
        padding-right: 30px;
    }

    .page-title-and-button{
        display:flex;
        justify-content: space-between;
    }


    .profile-pic {
        border-radius: 50px;
        height: 50px;
        width: 50px;
        object-fit: cover;
    }
    
    .employee-name{
        font-weight:bold;
    }

    .employee-role{
        color:rgba(80,80,80, 1);
    }

    .center {
        width: 75%;
        text-align: center;
    }
</style>

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color:#ffdcf4">
        <a class="nav-link pink-button-left" asp-controller="Home" asp-action="Index">Back</a>

        <div class="center">
            <h1 class="title">Worker Management</h1>
        </div>
    </nav>
</header>

<div style="padding-left: 200px; padding-right:200px;  padding-top: 50px;">

    <div class="background">
        <div class="page-title-and-button">
            <p class="page-title">Manage Workers</p>
                <a class="pink-button" asp-controller="Worker" asp-action="Invite">Invite an Employee</a>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>
                        <p>Worker</p>
                    </th>
                    <th>
                        <p>Name</p>
                    </th>
                    <th>
                        <p>Email</p>
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @if (item.UserImageData == null)
                            {
                                <img class="profile-pic" src="../images/default-profile-pic.jpg">
                            }
                            else
                            {
                                <img class="profile-pic" src="@Url.Action("RenderImage", new { id = item.UserId})" />
                            }
                        </td>
                        <td>
                            <div class="employee-name">
                                @Html.DisplayFor(modelItem => item.FirstName)
                                @Html.DisplayFor(modelItem => item.LastName)
                            </div>
                            <div class="employee-role">
                                @if (item.RoleId == 1)
                                {
                                    <p>Worker</p>
                                }
                                else if (item.RoleId == 2)
                                {
                                    <p>Manager</p>
                                }
                                else
                                {
                                    <p>Owner</p>
                                }
                            </div>

                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>

                        <td>
                            @if (item.RoleId == 3)
                            {
                                <a asp-action="OwnerSelfEdit" asp-route-id="@item.UserId">Edit</a>
                            }
                            else
                            {
                                <a asp-action="OwnerEdit" asp-route-id="@item.UserId">Edit</a>
                            }
                            |
                            <a asp-action="Details" asp-route-id="@item.UserId">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.UserId">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Worker/WorkerManagement.cshtml
@{
    ViewData["Title"] = "Worker Management";
}

    <head>
        <title>Worker Management</title>
        <style>

            body {
                font-family: arial;
                background-color: rgb(255, 244, 191);
            }

            .worker-display {
                display: flex;
                background-color: white;
                border-radius: 2px;
                box-shadow: 0px 0px 4px rgba(95, 94, 94, 0.3);
                height: 50px;
                align-items: center;
                max-width: 500px;
                justify-content: space-between;
                margin-bottom: 5px;
            }

            .worker-pfp {
                height: 30px;
                width: 30px;
                border-radius: 60px;
                margin-right: 15px;
                margin-left: 25px;
                object-fit: cover;
            }

            .worker-name {
                font-size: 15px;
                font-weight: 600;
                margin-right: 15px;
                margin-bottom: 0;
                margin-top: 0px;
            }

            .worker-role {
                font-size: 12px;
                margin-top: 0;
                margin-bottom: 0;
                color: gray;
            }

            .see-more-button {
                border: none;
                height: 30px;
                background-color: white;
                width: 30px;
                padding-right: 40px;
            }

            .see-more-icon {
                height: 30px;
            }

            .invite-employee {
                display: flex;
                border:none;
                background-color: rgb(244, 169, 182);
                color: white;
                border-radius: 2px;
                box-shadow: 0px 0px 3px rgba(95, 94, 94, 0.3);
                height: 50px;
                align-items: center;
                justify-content: center;
                width: 300px;
                margin-bottom: 2px;
                
            font-size: 15px;
            font-weight: 600;
            display: flex;
            }
        </style>
    </head>

    <h1 class="page-title">Worker Management</h1>
        <!--comment-->

        <!--Displays 1 worker name & role and a "view more" button in a single row-->
        <div class="worker-display">
            <div style="display: flex; align-items: center;">
            
            <img class="worker-pfp" src="@Url.Content("~/images/pompurrin.jpg")" />
                <div class="worker-info">
                    <p class="worker-name">Jane Smith</p>
                    <p class="worker-role">Barista</p>
                </div>
            </div>

            <div style="display: flex; align-items: center;">
                <button class="see-more-button">
                <img class="see-more-icon" src="@Url.Content("~/images/see-more-1.png")">
                </button>
            </div>
        </div>

        <!--Displays "invite employee"-->
        <button class="invite-employee">
            Invite Employee
        </button>
    