Models/Payroll.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace BaristaHome.Models
{
    public class Payroll
    {
        public int PayrollId { get; set; }
        public decimal Hours { get; set; }
        public decimal Amount { get; set; }

        [Column(TypeName = "Date")]
        public DateTime Date { get; set; }

        // Relationships
        public int UserId { get; set; }
        public virtual User? User { get; set; }
    }
}

Controllers/PayrollController.cs
using BaristaHome.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore.SqlServer;
using BaristaHome.Data;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BaristaHome.Controllers
{
    [Authorize]
    public class PayrollController : Controller
    {
        private readonly BaristaHomeContext _context;
        public PayrollController(BaristaHomeContext context)
        {
            _context = context;
        }


        /*        public IActionResult Worker()
                {
                    return View();
                }*/

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


        [HttpGet]
        public async Task<IActionResult> Worker(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var worker = await _context.User.FirstOrDefaultAsync(m => m.UserId == id);

            if (worker == null)
            {
                return NotFound();
            }

            List<Payroll> payrollQuery = (from u in _context.User
                                          join payroll in _context.Payroll on u.UserId equals payroll.UserId
                                          where payroll.UserId == worker.UserId
                                          select payroll).ToList();
            ViewBag.PayrollList = payrollQuery;

            return View(worker);
        }

        public async Task<ActionResult> RenderImage(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var worker = await _context.User
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (worker == null)
            {
                return NotFound();
            }
            var image = (from u in _context.User
                         where u.UserId == worker.UserId
                         select worker.UserImageData).First();


            return File(image, "image/png");
        }

        [HttpPost]
        public async Task<IActionResult> Worker(int month)
        {
            var userId = Convert.ToInt32(User.FindFirst("UserId").Value);
            var worker = await _context.User.FirstOrDefaultAsync(m => m.UserId == userId);
            //Get list of payroll
            var payrollList = (List<Payroll>)(from p in _context.Payroll
                                              where p.UserId == userId
                                              select p).ToList();
            ViewBag.PayrollList = payrollList;
            List<Payroll> resultPayroll = new List<Payroll>();
            if (month != null && month > 0)
            {
                resultPayroll = (from p in payrollList
                                where p.Date.Month == month
                                select p).ToList();
                ViewBag.PayrollList = resultPayroll;
            }
            else
            {
                resultPayroll = (from u in _context.User
                                              join payroll in _context.Payroll on u.UserId equals payroll.UserId
                                              where payroll.UserId == worker.UserId
                                              select payroll).ToList();
                ViewBag.PayrollList = resultPayroll;
            }

            return View(worker);


        }


        public async Task<IActionResult> Owner()
        {
            List<PayrollOwnerViewModel> payrolls = (from payroll in _context.Payroll
                                                    join user in _context.User on payroll.UserId equals user.UserId
                                                    join store in _context.Store on user.StoreId equals store.StoreId
                                                    where store.StoreId.Equals(Convert.ToInt16(User.FindFirst("StoreId").Value))
                                                    select new PayrollOwnerViewModel
                                                    {
                                                        Hours = payroll.Hours,
                                                        Amount = payroll.Amount,
                                                        Date = payroll.Date,
                                                        UserId = user.UserId,
                                                        FullName = user.FirstName + " " + user.LastName,
                                                        PayrollId = payroll.PayrollId,
                                                    }).OrderBy(o => o.FullName).ToList();

            ViewBag.Payroll = payrolls;

            ViewData["FullNames"] = new SelectList(payrolls, "UserId", "FullName");

            /* Pulls list of workers under the same store id for select list  */
            List<PayrollOwnerViewModel> users = (from user in _context.User
                                                 join store in _context.Store on user.StoreId equals store.StoreId
                                                 where store.StoreId.Equals(Convert.ToInt16(User.FindFirst("StoreId").Value))
                                                 select new PayrollOwnerViewModel
                                                 {
                                                     UserId = user.UserId,
                                                     FullName = user.FirstName + " " + user.LastName,
                                                 }).ToList();

            ViewData["FullNames"] = new SelectList(users, "UserId", "FullName");

            return View();
        }


        /* Adds a payroll into the database */
        [HttpPost]
        public async Task<IActionResult> Owner(PayrollOwnerViewModel payrollOwnerViewModel)
        {
            List<PayrollOwnerViewModel> payrolls = (from payroll in _context.Payroll
                                                    join user in _context.User on payroll.UserId equals user.UserId
                                                    join store in _context.Store on user.StoreId equals store.StoreId
                                                    where store.StoreId.Equals(Convert.ToInt16(User.FindFirst("StoreId").Value))
                                                    select new PayrollOwnerViewModel
                                                    {
                                                        Hours = payroll.Hours,
                                                        Amount = payroll.Amount,
                                                        Date = payroll.Date,
                                                        UserId = user.UserId,
                                                        FullName = user.FirstName + " " + user.LastName,
                                                        PayrollId = payroll.PayrollId,
                                                    }).OrderBy(o => o.FullName).ToList();
            ViewBag.Payroll = payrolls;

            ViewData["FullNames"] = new SelectList(payrolls, "UserId", "FullName");

            List<PayrollOwnerViewModel> users = (from user in _context.User
                                                 join store in _context.Store on user.StoreId equals store.StoreId
                                                 where store.StoreId.Equals(Convert.ToInt16(User.FindFirst("StoreId").Value))
                                                 select new PayrollOwnerViewModel
                                                 {
                                                     UserId = user.UserId,
                                                     FullName = user.FirstName + " " + user.LastName,
                                                 }).ToList();


            /* Shows the full name but when selected, it will give the userId as Value so database knows what user is being added */
            ViewData["FullNames"] = new SelectList(users, "UserId", "FullName");


            if (ModelState.IsValid)
            {
                var payroll1 = new Payroll()
                {
                    Hours = payrollOwnerViewModel.Hours,
                    Amount = payrollOwnerViewModel.Amount,
                    Date = payrollOwnerViewModel.Date,
                    UserId = payrollOwnerViewModel.UserId
                };

                _context.Add(payroll1);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Owner));


            }

            ViewData["FullNames"] = new SelectList(users, "FullName", "FullName");
            ModelState.AddModelError(string.Empty, "There was an issue adding this item into your Payroll");
            return View();

        }


        // Get: Payroll/Delete/PayrollId
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var PayrollEntry = await _context.Payroll.FirstOrDefaultAsync(m => m.PayrollId == id);

            if (PayrollEntry == null)
            {
                return NotFound();
            }

            var PayrollName = (from pr in _context.Payroll
                               join user in _context.User on pr.UserId equals user.UserId
                               where pr.PayrollId == id
                               select user.FirstName).FirstOrDefault();

            // Capitalizing first letter of name
            if (PayrollName.Length == 1)
                ViewBag.PayrollName = char.ToUpper(PayrollName[0]);

Views/Payroll/Delete.cshtml
@model BaristaHome.Models.Payroll

@{
    ViewData["Title"] = "Delete";
    Layout = null;
}

<style>
    .medium-btn {
        width: 70px;
        height: 30px;
    }

</style>

<!--Nav bar area-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Barista Home</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BaristaHome.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Menu.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Inventory.css" asp-append-version="true" />
</head>
<body>
    <!--Nav bar area-->
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color:#ffdcf4">
            <a class="nav-link pink-button-left" asp-area="" asp-controller="" asp-action="">Home</a>
            <div class="center">
                <h1 class="title">Delete Payroll</h1>
            </div>
            <a class="nav-link pink-button-right" asp-area="" asp-controller="Payroll" asp-action="Owner">Payrolls</a>
        </nav>
    </header>

    <div class="container">
        <h3>Are you sure you want to delete this?</h3>

        <div>
            @*<h4>Payroll</h4>*@
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Hours)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Hours)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Amount)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Amount)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Date)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Date)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.User)
                </dt>
                <dd class="col-sm-10">
                    @ViewBag.PayrollName
                </dd>
            </dl>

        </div>

        <form asp-action="Delete">
            <input type="hidden" asp-for="PayrollId" />
            <input type="submit" value="Delete" class="medium-btn" /> |
            <a asp-action="Owner">Back to List</a>
        </form>
    </div>
</body>
</html>

Views/Payroll/Edit.cshtml
@model BaristaHome.Models.Payroll

@{
    ViewData["Title"] = "Edit";
    Layout = null;
}

<link rel="stylesheet" href="~/css/Inventory.css" asp-append-version="true" />

<!--Nav bar area-->
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Barista Home</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BaristaHome.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Menu.css" asp-append-version="true" /> <!--Stylesheet-->
</head>
<body>
    <!--Nav bar area-->
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color:#ffdcf4">
            <a class="nav-link pink-button-left" asp-area="" asp-controller="Payroll" asp-action="Owner">Back</a>
            <div class="center">
                <h1 class="title">Edit Payroll</h1>
            </div>
        </nav>
    </header>



</body>
</html>

<div class="container">
    <div class="col-md-4" style="margin: 0 auto;">
        <h4>@ViewBag.PayrollName</h4>
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PayrollId" />
            <input type="hidden" asp-for="UserId" />
            <div class="form-group">
                <label asp-for="Hours" class="control-label"></label>
                <input asp-for="Hours" class="form-control" />
                <span asp-validation-for="Hours" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" type="datetime-local" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" style="width: 100px; margin-top: 50px"/>
            </div>
        </form>
    </div>

@*    <div>
        <a asp-action="Owner">Back to List</a>
    </div>*@
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Payroll/Owner.cshtml
@*@model IEnumerable<BaristaHome.Models.PayrollOwnerViewModel>*@

@model BaristaHome.Models.PayrollOwnerViewModel


@{
    ViewData["Title"] = "Owner";
    Layout = null;
}

<link rel="stylesheet" href="~/css/Inventory.css" asp-append-version="true" />



<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Barista Home</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BaristaHome.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Menu.css" asp-append-version="true" /> <!--Stylesheet-->
</head>
<body>
    <!--Nav bar area-->
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color:#ffdcf4">
            <a class="nav-link pink-button-left" asp-area="" asp-controller="" asp-action="">Home</a>
            <div class="center">
                <h1 class="title">Payroll Management</h1>
            </div>
            @*<a class="nav-link pink-button-right" asp-area="" asp-controller="" asp-action="">Add Payroll</a>*@
            <a class="nav-link pink-button-right" data-toggle="modal" data-target="#payrollModal">Add Payroll</a>
        </nav>
    </header>

    <footer class="border-top footer text-muted">
        <div class="container">
-webkit-align-items      &copy; 2022 - Barista Home - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>


<style>
    .flex-container {
        display: flex;
        justify-content: space-between;
        margin-right: auto;
        margin-left: auto;
        width: 92%;
        height: 70px;
    }
</style>



<div class="flex-container">

    <form asp-action="SearchBarResults">
        <div style="width: 700px;" class="input-group mb-3">
            <label for="searchPhrase" class="control-label"></label>
            <select asp-for="UserId" class="form-control" asp-items="ViewBag.FullNames"></select>
            @*<input type="text" name="searchPhrase" class="form-control" placeholder="Search" aria-label="Recipient's username">*@

            <div class="input-group-append">
                <button style="background-color: #ffdcf4;
                                         border-color:#ffdcf4;
                                         color:black;" class="btn btn-outline-secondary" type="submit">
                   Filter By Name
                </button>
            </div>
        </div>
    </form>


</div>






<table class="table-inventory">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hours)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
           
            var payrollList = ViewBag.Payroll == null ? new List<PayrollOwnerViewModel>() : (List<PayrollOwnerViewModel>)ViewBag.Payroll;
            if (payrollList.Any())
            {
                foreach (var item in payrollList)
                {
                    var dataTargetEdit = "#ModalEdit" + item.PayrollId;
                    var modalID = "ModalEdit" + item.PayrollId;

                    <tr>
                        <td>
                            @item.FullName
                        </td>
                        <td>
                            @item.Hours
                        </td>
                        <td>
                            @item.Amount
                        </td>
                        <td>
                            @item.Date.ToShortDateString()
                        </td>
                        <td>
                            <a class="img-size" >
                                <img src="../images/editButton.png"  data-toggle= "modal" data-target="@dataTargetEdit" style="cursor: pointer">
                            </a>


                            <div class="modal fade" id="@modalID" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-sm" role="document">
                                    <div class="modal-content" style="margin-top: 300px;">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="editModalLabel">Select Action</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="center" style="align-items: center">
                                                <a class="btn btn-outline-dark" asp-action="Edit" asp-route-id="@item.PayrollId" style="width:80px">Edit</a>
                                                <a class="btn btn-outline-dark" asp-action="Delete" asp-route-id="@item.PayrollId" style="width:80px">Delete</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>




                            @*<a class="btn btn-outline-dark" asp-action="Delete" asp-route-id="@item.PayrollId">Delete</a>
                            <a class="btn btn-outline-dark" asp-action="Edit" asp-route-id="@item.PayrollId">Edit</a> *@
                            
                        </td>
                    </tr>
                }
            }
        }
    </tbody>
</table>

@* Import bootstrap for modal (Need more research on why these ones are used)*@
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


@* Background and color for buttons in pop up window*@
<style>
    .modal-content {
        background: #ffe4b4;
    }

    .btn-primary, .btn-outline-dark {
        background-color: #ffdcf4 !important;
    }
</style>

@* Code for the modal pop up of New Payroll *@
<div class="modal fade" id="payrollModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Add Item</h2>
            </div>
            <div class="modal-body">
                <form method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>


                    <label class="control-label"> Name</label>
                    <select asp-for="UserId" class="form-control" style="text-transform:capitalize" asp-items="ViewBag.FullNames"></select>

                    <div class="form-group">
                        <label asp-for="Hours"></label>
                        <input asp-for="Hours" class="form-control" />
                        <span asp-validation-for="Hours" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Amount"></label>
                        <input asp-for="Amount" class="form-control" />
                        <span asp-validation-for="Amount" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="control-label">Date</label>
                        <input asp-for ="Date" type="datetime-local" class="form-control" />
                        <span asp-validation-for="Date" class="text-danger"></span>
                    </div>


                    <div class="modal-footer">
                        <div class="btn-group">
                            <input type="submit" value="Save" class="btn btn-outline-dark m-1" />
                            <a class="btn btn-outline-dark m-1" asp-area="" asp-controller="Payroll" asp-action="Owner">Cancel</a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

Views/Payroll/Worker.cshtml
@model BaristaHome.Models.User
@{
    ViewData["Title"] = "Worker";
    Layout = null;
}

<div class="text-center">
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] • Barista Home</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BaristaHome.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Payroll.css" asp-append-version="true" /> <!--Stylesheet-->
</head>

<body>
    <!--Nav bar area-->
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color:#ffdcf4">
            <a class="nav-link pink-button-left" asp-area="" asp-controller="" asp-action="">Back</a>
            <div class="center">
                <a class="text-black title" asp-area="" asp-controller="Payroll" asp-action="Worker">Payroll View</a>
            </div>
        </nav>
    </header>

    <div align="center">
        <div class="worker">
            <div class="picture">
                @*Drink image*@
                <div class="user-icon">
                    @*Display default icon if drink has no image*@
                    @if(Model.UserImageData ==null)
                    {
                        <img class="user-icon image" src="@Url.Content("~/images/default-profile-pic.jpg")"> //Default image display
                       
                    }
                    else
                    {
                        <img class="user-icon image" src="@Url.Action("RenderImage", new { id = Model.UserId})" />
                    }
                </div>
            </div>
            <div class="name-area">
                <div class="name">@Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)</div>
            </div>
        </div>

        <div class="information">
            <table class="table-payroll" style="width:100%">
                <form asp-action="Worker">
                    <div class="filter" style="float:left;">
                        <select placeholder="Select Month" name="month">
                            <option value="">All</option>
                            <option value="1">January</option>
                            <option value="2">February</option>
                            <option value="3">March</option>
                            <option value="4">April</option>
                            <option value="5">May</option>
                            <option value="6">June</option>
                            <option value="7">July</option>
                            <option value="8">August</option>
                            <option value="9">September</option>
                            <option value="10">October</option>
                            <option value="11">November</option>
                            <option value="12">December</option>
                        </select>
                        <input type="submit" asp-action="Worker" value="Filter" style="fit-content;">
                    </div>
                </form>
                <tr style="background-color:#ffdcf4; height:70px">
                    <td style="width:50%">
                        Date
                    </td>
                    <td style="width:20%">Hours</td>
                    <td style="width:30%">Amount</td>
                </tr>
                @{
                    var myList = ViewBag.PayrollList==null ? new List<Payroll>() : (List<Payroll>)ViewBag.PayrollList;
                    if(myList.Any()) {
                        foreach(var p in myList) {
                            <tr style="height:70px">
                                <td style="width:33.33%">@p.Date.Month/@p.Date.Day/@p.Date.Year</td>
                                <td style="width:33.33%">@p.Hours</td>
                                <td style="width:33.33%">@p.Amount</td>
                            </tr>
                        }
                    }
                }
            </table>
        </div>
    </div>


</body>

</html>